@baseUrl = http://localhost:4000
@categoryId = 6905cae7ad1bd284aa992433
@productCode = SP001

# CREATE CATEGORY
POST {{baseUrl}}/category
Content-Type: application/json

{
  "name": "VIP Section",
  "code": "A125",
  "color": "#FF0000",
  "seatType": "RS",
  "description": "Reserved seating near stage",
  "productCode": "{{productCode}}"
}

####

# GET ALL CATEGORIES
GET {{baseUrl}}/category
####


# GET CATEGORY BY ID
GET {{baseUrl}}/category/{{categoryId}}
####


# UPDATE CATEGORY (partial)
PUT {{baseUrl}}/category/ab0ca912-2626-4d7f-b548-fb7a14cb34fc
Content-Type: application/json

{
  "name": "Premium Section",
  "color": "#00FF00",
  "description": "Updated description"
}
####

# DELETE CATEGORY
DELETE {{baseUrl}}/category/6b365187-02ca-464a-9d07-69da13929254
####
