@baseUrl = http://localhost:4000
@categoryId = 6905cae7ad1bd284aa992433
@productCode = SP000007

# CREATE CATEGORY
POST {{baseUrl}}/{{productCode}}/category
Content-Type: application/json

{
  "name": "General Admission",
  "code": "GA18",
  "color": "#800080",
  "seatType": "GA",
  "description": "All Entry"
}

####

# GET ALL CATEGORIES
GET {{baseUrl}}/{{productCode}}category
####


# GET CATEGORY BY ID
GET {{baseUrl}}{{productCode}}/category/{{categoryId}}
####


# UPDATE CATEGORY (partial)
PUT {{baseUrl}}/{{productCode}}category/523f87a7-c5f6-4d7e-b88c-e6281cfa6f0f
Content-Type: application/json

{
  "name": "Premium Section",
  "color": "#00FF00",
  "description": "Updated description"
}
####

# DELETE CATEGORY
DELETE {{baseUrl}}/{{productCode}}category/6b365187-02ca-464a-9d07-69da13929254
####
