# Define a variable for base URL
@baseUrl = http://localhost:4000
@productId = 6905cae7ad1bd284aa992433

### Create a new product
POST {{baseUrl}}/products
Content-Type: application/json

{
  "name": "Sample Product",
  "code": "SP000007",
  "currency": "USD",
  "timeZone": "America/New_York",
  "type": "event"
}

### Update a product
PUT {{baseUrl}}/products/{{productId}}
Content-Type: application/json

{
  "stopSales": false,
  "name": "Updated Product Name",
  "bannerImage": "https://example.com/banner.jpg",
  "cardImage": "https://example.com/card.jpg",
  "socialMedia": [
    { "name": "Twitter", "url": "https://twitter.com/sample" },
    { "name": "Facebook", "url": "https://facebook.com/sample" }
  ]
}

### Get all products
GET {{baseUrl}}/products

### Get a single product
GET {{baseUrl}}/products/{{productId}}