# ===============================
# 🌐 Base URL Configuration
# ===============================
@baseUrl = http://localhost:4000
@productCode = SP000007
@ticketTypeId = ebfb2898-ac97-4e00-9241-e730c64ce394
# ===============================
# 🟢 Create a new Ticket Type
# ===============================
POST {{baseUrl}}/{{productCode}}/ticket-types
Content-Type: application/json

{
  "code": "1234",
  "name": "VIP Ticket",
  "category": "A126",
  "price": 150,
  "minQty": 5,
  "maxQty": 10,
  "quota": 100,
  "complimentary": false,
  "expiryRelative": null,
  "expirySpecific": null
}

####
# ===============================
# 📄 Get all Ticket Types
# ===============================
GET {{baseUrl}}/{{productCode}}/ticket-types
###
# ===============================
# 📄 Get a single Ticket Type
# ===============================
GET {{baseUrl}}/{{productCode}}/ticket-types/{{ticketTypeId}}
####
# ===============================
# ✏️ Update a Ticket Type
# ===============================
PUT {{baseUrl}}/{{productCode}}/ticket-types/{{ticketTypeId}}
Content-Type: application/json

{
  "name": "VIP Ticket Updated",
  "price": 0,
  "minQty": 2,
  "maxQty": 12,
  "quota": 150,
  "complimentary": true,
  "expiryRelative": null,
  "expirySpecific": null
}

####
# ===============================
# ❌ Delete a Ticket Type
# ===============================
DELETE {{baseUrl}}/{{productCode}}/ticket-types/{{ticketTypeId}}
